# Use a base image with Java 11
FROM openjdk:11-jre-slim

# Create a directory for the application
WORKDIR /app

# Copy the JAR file into the container
COPY target/java-maven-ecr-demo-*.jar app.jar

# Expose the port your app runs on (if applicable)
# EXPOSE 8080

# Command to run the application
ENTRYPOINT ["java", "-jar", "app.jar"]