name: java-application-maven

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    
    - name: Setup Java JDK
      uses: actions/setup-java@v3.14.1
      with:
        java-version: '17'
        distribution: 'oracle'
  
    - name: building the package
      run: |
          mvn test
  sonar_scan:
    runs-on: self-hosted
    needs: test
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Setup Java JDK
      uses: actions/setup-java@v3.14.1
      with:
        java-version: '17'
        distribution: 'oracle'

    - name: Build Project
      run: mvn package

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-jar
        path: target/*.jar


